language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04
mono: latest
dotnet : 2.2.108

before_install:
 - export PATH=$PATH:/home/travis/.dotnet/tools
 - dotnet tool install paket -g
 - dotnet restore build.proj

script:
 - dotnet fake build --target Linux

branches:
  except:
    - gh-pages
    - nuget